{"name":"Local: try_except","url":"e:\\Phitron\\OOP and Python Programming\\Module 3\\try_except.py","tests":[{"id":1695748203422,"input":"","output":""}],"interactive":false,"memoryLimit":1024,"timeLimit":3000,"srcPath":"e:\\Phitron\\OOP and Python Programming\\Module 3\\try_except.py","group":"local","local":true}